# Generated by Django 4.2.21 on 2025-05-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_cover',
            field=models.ImageField(blank=True, null=True, upload_to='thread/'),
        ),
    ]
