# Generated by Django 4.2.21 on 2025-05-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_thread_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
