# Generated by Django 4.2.21 on 2025-05-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
