# Generated by Django 4.2.21 on 2025-05-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chatbot_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
